Repository AY2324S1-CS2103T-W15-2/tp, pull requests merged in 2023-10, with the labels that each got.

#160 Update UG - Zann
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.Medium

#155 148 update dg commands
  docs/DeveloperGuide.md
  docs/diagrams/CreateDeadlineCommandSequenceDiagram.puml
  docs/diagrams/CreateStudentCommandSequenceDiagram.puml
  docs/diagrams/EditCommandSequenceDiagram.puml
Labels: priority.High

#167 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/model/profbook/Group.java
  src/main/java/seedu/address/model/profbook/Student.java
  src/main/java/seedu/address/model/taskmanager/Deadline.java
  src/main/java/seedu/address/model/taskmanager/ToDo.java
  src/main/java/seedu/address/ui/DeadlineCard.java
  src/main/java/seedu/address/ui/Displayable.java
  src/main/java/seedu/address/ui/GroupCard.java
  src/main/java/seedu/address/ui/ItemCard.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TodoCard.java
Labels: priority.High

#164 Update UG
  docs/UserGuide.md
Labels: priority.High

#162 Update UG
  build.gradle
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/Ui.png
  docs/stylesheets/main.css
Labels: priority.High

#168 166 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteTaskSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
Labels: priority.High

#179 Edit tasklist inheritance and improve immutability
  src/main/java/seedu/address/logic/commands/CreateDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/CreateTodoCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/CreateDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateTodoCommandParser.java
  src/main/java/seedu/address/model/ChildOperation.java
  src/main/java/seedu/address/model/IChildOperation.java
  src/main/java/seedu/address/model/ITaskOperations.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskOperation.java
  src/main/java/seedu/address/model/profbook/ChildrenAndTaskListManager.java
  src/main/java/seedu/address/model/profbook/ChildrenManager.java
  src/main/java/seedu/address/model/profbook/Group.java
  src/main/java/seedu/address/model/profbook/IChildElement.java
  src/main/java/seedu/address/model/profbook/Root.java
  src/main/java/seedu/address/model/profbook/Student.java
  src/main/java/seedu/address/model/profbook/TaskListManager.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/ReadOnlyTaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskListManager.java
  src/main/java/seedu/address/model/task/ToDo.java
  src/main/java/seedu/address/model/task/exceptions/NoSuchTaskException.java
  src/main/java/seedu/address/model/taskmanager/TaskList.java
  src/main/java/seedu/address/model/util/SampleProfBook.java
  src/main/java/seedu/address/storage/JsonAdaptedDeadline.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTasks.java
  src/main/java/seedu/address/storage/JsonAdaptedToDo.java
  src/main/java/seedu/address/ui/DeadlineCard.java
  src/main/java/seedu/address/ui/TodoCard.java
  src/test/java/seedu/address/logic/commands/CreateDeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateTodoCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/MoveStudentToGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/logic/parser/CreateDeadlineCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CreateStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CreateTodoCommandParserTest.java
  src/test/java/seedu/address/model/taskmanager/TaskListTest.java
  src/test/java/seedu/address/statemanager/ChildOperationTest.java
  src/test/java/seedu/address/statemanager/TaskOperationTest.java
  src/test/java/seedu/address/testutil/GroupBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: type.Task, priority.High

#180 Remove compulsory options for create student command
  src/main/java/seedu/address/logic/parser/CreateStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/profbook/Address.java
  src/main/java/seedu/address/model/profbook/Email.java
  src/main/java/seedu/address/model/profbook/Phone.java
Labels: type.Task, priority.High

#187 Add Exit Command and Clear Command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/ProfBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/path/AbsolutePath.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
Labels: type.Task, priority.High

#189 Fix bugs check duplicates id in ProfBook
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
  src/main/java/seedu/address/logic/commands/CreateStudentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/field/EditGroupDescriptor.java
  src/main/java/seedu/address/model/profbook/Email.java
  src/main/java/seedu/address/model/profbook/Name.java
  src/test/java/seedu/address/logic/commands/CreateGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateStudentCommandTest.java
Labels: type.Bug, priority.High

#195 Use current path as default path if no path provided
  src/main/java/seedu/address/logic/commands/CreateTodoCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CreateDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateTodoCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/path/RelativePath.java
  src/main/java/seedu/address/model/path/element/PathElement.java
  src/test/java/seedu/address/model/path/AbsolutePathTest.java
Labels: type.Enhancement

#199 Validate options
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CreateDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateTodoCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteForStudentsAndGroupsCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/MoveStudentToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ShowChildrenListCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowTaskListCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
Labels: type.Bug, priority.High

#202 Add help option for all commands
  src/main/java/seedu/address/logic/commands/ChangeDirectoryCommand.java
  src/main/java/seedu/address/logic/commands/CreateDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
  src/main/java/seedu/address/logic/commands/CreateStudentCommand.java
  src/main/java/seedu/address/logic/commands/CreateTodoCommand.java
  src/main/java/seedu/address/logic/commands/DeleteForStudentsAndGroupsCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/MoveStudentToGroupCommand.java
  src/main/java/seedu/address/logic/commands/ShowChildrenListCommand.java
  src/main/java/seedu/address/logic/commands/ShowTaskListCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/ChangeDirectoryCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateTodoCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteForStudentsAndGroupsCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/MoveStudentToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowChildrenListCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowTaskListCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
Labels: type.Enhancement
