Repository AY2324S1-CS2103T-W15-2/tp, pull requests merged in 2023-11, with the labels that each got.

#198 Show display path in GUI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/ItemListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ItemListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: type.Enhancement

#197 Update message usage and return message
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ChangeDirectoryCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CreateDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
  src/main/java/seedu/address/logic/commands/CreateStudentCommand.java
  src/main/java/seedu/address/logic/commands/CreateTodoCommand.java
  src/main/java/seedu/address/logic/commands/DeleteForStudentsAndGroupsCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/MoveStudentToGroupCommand.java
  src/main/java/seedu/address/logic/commands/ShowChildrenListCommand.java
  src/main/java/seedu/address/logic/commands/ShowTaskListCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/test/java/seedu/address/logic/commands/CreateDeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateTodoCommandTest.java
Labels: priority.High, severity.High

#203 Fix unordered list when storing data
  src/main/java/seedu/address/model/profbook/ChildrenManager.java
  src/main/java/seedu/address/model/profbook/Group.java
  src/main/java/seedu/address/model/profbook/IChildElement.java
  src/main/java/seedu/address/model/profbook/Student.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
Labels: type.Bug, priority.High

#205 Enhance TaskList and Children Manager
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CreateStudentCommandParser.java
  src/main/java/seedu/address/model/ChildOperation.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskOperation.java
  src/main/java/seedu/address/model/profbook/ChildrenAndTaskListManager.java
  src/main/java/seedu/address/model/profbook/ChildrenManager.java
  src/main/java/seedu/address/model/profbook/IChildrenManager.java
  src/main/java/seedu/address/model/task/ITaskListManager.java
  src/main/java/seedu/address/model/task/ReadOnlyTaskList.java
  src/main/java/seedu/address/model/task/TaskListManager.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/test/java/seedu/address/logic/commands/MoveStudentToGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/CreateStudentCommandParserTest.java
  src/test/java/seedu/address/statemanager/ChildOperationTest.java
  src/test/java/seedu/address/statemanager/TaskOperationTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Enhancement

#190 184 Update UG
  docs/UserGuide.md
  docs/package-lock.json
Labels: type.Enhancement, type.Task

#207 Fix general bugs
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ChangeDirectoryCommand.java
  src/main/java/seedu/address/logic/commands/CreateDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
  src/main/java/seedu/address/logic/commands/CreateStudentCommand.java
  src/main/java/seedu/address/logic/commands/CreateTodoCommand.java
  src/main/java/seedu/address/logic/commands/DeleteForStudentsAndGroupsCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/MoveStudentToGroupCommand.java
  src/main/java/seedu/address/logic/commands/ShowChildrenListCommand.java
  src/main/java/seedu/address/logic/commands/ShowTaskListCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CreateDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateTodoCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteForStudentsAndGroupsCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/MoveStudentToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/Option.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/main/java/seedu/address/model/profbook/Address.java
  src/main/java/seedu/address/model/profbook/Email.java
  src/main/java/seedu/address/model/profbook/Phone.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CreateDeadlineCommandTest.java
Labels: type.Bug, priority.High, severity.High

#209 Fix messages
  src/main/java/seedu/address/logic/commands/CreateStudentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/ShowChildrenListCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/ChangeDirectoryCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/id/GroupId.java
  src/main/java/seedu/address/model/id/StudentId.java
  src/main/java/seedu/address/model/util/SampleProfBook.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.High

#192 178 update testing storage
  src/main/java/seedu/address/model/ChildOperation.java
  src/main/java/seedu/address/model/IChildOperation.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedTasks.java
  src/test/data/JsonProfBookStorageTest/invalidAndValidRoot.json
  src/test/data/JsonProfBookStorageTest/notJsonFormatProfBook.json
  src/test/data/JsonProfBookStorageTestJson/invalidAndValidPersonAddressBook.json
  src/test/data/JsonProfBookStorageTestJson/invalidPersonAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/model/ChildOperationTest.java
  src/test/java/seedu/address/model/TaskOperationTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/task/DeadlineTest.java
  src/test/java/seedu/address/model/task/ReadOnlyTaskListTest.java
  src/test/java/seedu/address/model/task/TaskListManagerTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/ToDoTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDeadlineTest.java
  src/test/java/seedu/address/storage/JsonAdaptedGroupTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRootTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedToDoTest.java
  src/test/java/seedu/address/storage/JsonProfBookStorageTest.java
  src/test/java/seedu/address/storage/ProfBookStorageManagerTest.java
Labels: type.Enhancement

#260 Add unit test
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ChangeDirectoryCommand.java
  src/main/java/seedu/address/logic/commands/DeleteForStudentsAndGroupsCommand.java
  src/main/java/seedu/address/logic/commands/ShowChildrenListCommand.java
  src/main/java/seedu/address/logic/commands/ShowTaskListCommand.java
  src/main/java/seedu/address/logic/parser/ChangeDirectoryCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ShowChildrenListCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowTaskListCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/id/exceptions/InvalidIdException.java
  src/main/java/seedu/address/model/path/AbsolutePath.java
  src/main/java/seedu/address/model/path/Path.java
  src/main/java/seedu/address/model/path/element/PathElement.java
  src/main/java/seedu/address/model/path/exceptions/UnsupportedPathOperationException.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ChangeDirectoryCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CreateDeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowChildrenListCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowTaskListCommandTest.java
  src/test/java/seedu/address/logic/parser/ChangeDirectoryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ProfBookParserTest.java
  src/test/java/seedu/address/logic/parser/ShowChildrenListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ShowTaskListCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/id/GroupIdTest.java
  src/test/java/seedu/address/model/id/StudentIdTest.java
  src/test/java/seedu/address/model/path/AbsolutePathTest.java
  src/test/java/seedu/address/model/path/RelativePathTest.java
  src/test/java/seedu/address/model/path/element/PathElementTest.java
  src/test/java/seedu/address/testutil/GroupBuilder.java
  src/test/java/seedu/address/testutil/PathBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPaths.java
  src/test/java/seedu/address/testutil/TypicalRoots.java
Labels: type.Task

#266 Fix task creation with empty description bug
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/CreateDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateTodoCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, type.FunctionalityBug

#267 Fix duplicate task creation bug
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Task.java
Labels: priority.High, type.FunctionalityBug

#268 Fix UI bugs
  src/main/java/seedu/address/ui/GroupCard.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DeadlineCard.fxml
  src/main/resources/view/GroupCard.fxml
  src/main/resources/view/ItemListPanel.fxml
  src/main/resources/view/StudentCard.fxml
  src/main/resources/view/TodoCard.fxml
Labels: priority.High, type.FunctionalityBug

#262 Edit UG
  docs/UserGuide.md
  docs/images/groupdirectoryimage.png
  docs/images/listimage.png
  docs/images/rootdirectoryimage.png
Labels: priority.Medium

#273 Update PPP
  docs/team/zannloo.md
Labels: priority.Medium

#275 Improve code quality
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ChangeDirectoryCommand.java
  src/main/java/seedu/address/logic/commands/CreateDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
  src/main/java/seedu/address/logic/commands/CreateStudentCommand.java
  src/main/java/seedu/address/logic/commands/CreateTodoCommand.java
  src/main/java/seedu/address/logic/commands/DeleteForStudentsAndGroupsCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/MoveStudentToGroupCommand.java
  src/main/java/seedu/address/logic/commands/ShowChildrenListCommand.java
  src/main/java/seedu/address/logic/commands/ShowTaskListCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/ChangeDirectoryCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateTodoCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteForStudentsAndGroupsCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/MoveStudentToGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/Option.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ProfBookParser.java
  src/main/java/seedu/address/logic/parser/ShowChildrenListCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowTaskListCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/main/java/seedu/address/model/ChildOperation.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/id/GroupId.java
  src/main/java/seedu/address/model/id/StudentId.java
  src/main/java/seedu/address/model/path/AbsolutePath.java
  src/main/java/seedu/address/model/path/Path.java
  src/main/java/seedu/address/model/path/RelativePath.java
  src/main/java/seedu/address/model/path/element/PathElement.java
  src/main/java/seedu/address/model/path/element/PathElementType.java
  src/main/java/seedu/address/model/path/element/exceptions/InvalidPathElementException.java
  src/main/java/seedu/address/model/profbook/ChildrenAndTaskListManager.java
  src/test/java/seedu/address/logic/parser/ChangeDirectoryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ShowChildrenListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ShowTaskListCommandParserTest.java
Labels: priority.High

#277 Update PPP
  docs/stylesheets/main.css
  docs/team/nereuswb922.md
Labels: priority.High

#280 Update PPP
  docs/team/ngchunman.md
Labels: priority.High

#284 282 check code quality
  src/main/java/seedu/address/logic/commands/CreateDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/CreateStudentCommand.java
  src/main/java/seedu/address/logic/commands/CreateTodoCommand.java
  src/main/java/seedu/address/logic/commands/DeleteForStudentsAndGroupsCommand.java
  src/test/java/seedu/address/logic/commands/CreateDeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateTodoCommandTest.java
Labels: priority.Medium

#296 Update Use cases, Glossary
  docs/DeveloperGuide.md
Labels: priority.High

#297 Refactor edit
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/ChildOperation.java
  src/main/java/seedu/address/model/IChildOperation.java
  src/main/java/seedu/address/model/field/EditDescriptor.java
  src/main/java/seedu/address/model/field/EditGroupDescriptor.java
  src/main/java/seedu/address/model/field/EditStudentDescriptor.java
Labels: priority.High

#318 Update ui, homepage and readme
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/groupdirectoryimage.png
  docs/images/listimage.png
  docs/images/rootdirectoryimage.png
  docs/index.md
Labels: priority.High
